# Generated by Django 3.0.8 on 2020-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(default='https://via.placeholder.com/490', max_length=512, verbose_name='이미지주소'),
            preserve_default=False,
        ),
    ]
